label:
  en: Meta
  ru: Мета
columns:
  - width: 1/1
    sections:
      head:
        type: info
        headline:
          en: Info
          ru: Информация
        text:
          en: |
            Values for meta-tags and Open Graph markup.
            These values can be overridden for each page in the Meta tab.
          ru: |
            Значения мета-тегов и Open Graph разметки.
            Данные значения можно переопределить для каждой страницы во вкладке «Мета».
  - width: 2/3
    sections:
      meta:
        type: fields
        fields:
          meta_title:
            label: Title
            type: text
          meta_desc:
            label: Description
            type: textarea
            size: small
            buttons: false
          og_info:
            label:
            type: info
            text:
              en: |
                [__Open Graph__](https://yandex.ru/support/webmaster/open-graph/intro-open-graph.html?lang=ru)
                Markup for previewing links on social networks.
              ru: |
                [__Open Graph__](https://yandex.ru/support/webmaster/open-graph/intro-open-graph.html?lang=ru)
                Разметка для превью ссылки в социальных сетях.
          og_title:
            label: og:title
            type: text
            width: 1/2
          og_site:
            label: og:site_name
            type: text
            width: 1/2
          og_desc:
            label: og:description
            type: textarea
            size: small
            buttons: false
  - width: 1/3
    sections:
      shareimg:
        headline:
          en: Share picture
          ru: Изображение для шаринга
        type: files
        max: 1
        layout: cards
        info: "{{ file.dimensions }}"
        sortable: false
        template: share
        size: large
        help:
          en: Image size __1200×630px__
          ru: Размер изображения __1200×630px__
        image:
          back: black
          ratio: 3/2
